In [2]:
import pandas as pd
import numpy as np
import math

In [3]:
data1=pd.read_csv('datasets/ProcessedData/data1.1.csv')
data2=pd.read_csv('datasets/ProcessedData/data2.1.csv')
data3=pd.read_csv('datasets/ProcessedData/data3.1.csv')
data4=pd.read_csv('datasets/ProcessedData/data4.1.csv')
data5=pd.read_csv('datasets/ProcessedData/data5.1.csv')

C:\Users\jiaom\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (22,23,24,25,26,27,28) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
data1.head()
len(data1.iloc[0][:])

29

In [5]:
data2.head()

,Condition,Symptom1,Symptom2,Symptom3,Symptom4,Symptom5,Symptom6,Symptom7,Symptom8,Symptom9,...,Symptom19,Symptom20,Symptom21,Symptom22,Symptom23,Symptom24,Symptom25,Symptom26,Symptom26.1,Symptom28
0,hypertensive disease,pain chest,shortness of breath,dizziness,asthenia,fall,syncope,vertigo,sweating increased,palpitation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,hypertensive disease,pain chest,shortness of breath,dizziness,asthenia,fall,syncope,vertigo,sweating increased,palpitation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,hypertensive disease,pain chest,shortness of breath,dizziness,asthenia,fall,syncope,vertigo,sweating increased,palpitation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,hypertensive disease,pain chest,shortness of breath,dizziness,asthenia,fall,syncope,vertigo,sweating increased,palpitation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,hypertensive disease,pain chest,shortness of breath,dizziness,asthenia,fall,syncope,vertigo,sweating increased,palpitation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data3.head()
data3.describe(include='all')

,Condition,Symptom1,Symptom2,Symptom3,Symptom4,Symptom5,Symptom6,Symptom7,Symptom8,Symptom9,...,Symptom19,Symptom20,Symptom21,Symptom22,Symptom23,Symptom24,Symptom25,Symptom26,Symptom27,Symptom28
count,1048575,1048575,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,4088,176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Obesity,Pain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,68099,106029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data4.head()
len(data4.iloc[0][:])

29

In [8]:
data5.head()
len(data5.iloc[0][:])

29

In [9]:
test = pd.DataFrame([[3,4,6],[5,8,3]])
test2 = pd.DataFrame([[1,2],[5,7,7]])
test3 = pd.concat([test,test2])
test3.head()

   0  1    2
0  3  4  6.0
1  5  8  3.0
0  1  2  NaN
1  5  7  7.0

In [10]:
data = pd.concat([data1,data2,data3,data4,data5], axis=0)
len(data)

1087273

In [11]:
sum = len(data1) + len(data2) + len(data3) + len(data4) + len(data5)
print(sum)
#testing for loss

1087273

In [12]:
data.head()

,Condition,Symptom1,Symptom2,Symptom3,Symptom4,Symptom5,Symptom6,Symptom7,Symptom8,Symptom9,...,Symptom20,Symptom21,Symptom22,Symptom23,Symptom24,Symptom25,Symptom26,Symptom27,Symptom28,Symptom26.1
0,Peripheral Nervous System Diseases,Body Weight,Drug effect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Hypertension,Body Weight,Drug effect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Toxoplasmosis, Animal",Body Weight,Drug effect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Prostatic Neoplasms,Body Weight,Drug effect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Epilepsy;Vision Disorders,Vision Disorders,Drug side effect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
print(len(data.iloc[0][:]))

30

In [14]:
data.describe(include='all')

,Condition,Symptom1,Symptom2,Symptom3,Symptom4,Symptom5,Symptom6,Symptom7,Symptom8,Symptom9,...,Symptom20,Symptom21,Symptom22,Symptom23,Symptom24,Symptom25,Symptom26,Symptom27,Symptom28,Symptom26.1
count,1087273,1087273,38698,38656,38299,37048,36616,35854,34445,33051,...,4626,3529,1590,1310,1033,643,376,0.0,376,376
unique,4256,328,177,192,178,143,129,129,114,113,...,15,12,7,6,3,3,2,NaN,2,2
top,Obesity,Pain,shortness of breath,shortness of breath,asthenia,fall,syncope,vertigo,sweating increased,palpitation,...,unable to concentrate,homelessness,pain,consciousness clear,nightmare,consciousness clear,blackout,NaN,exhaustion,tremor
freq,68101,106029,3689,3783,3710,4169,4234,3363,3528,3549,...,1337,1337,390,390,657,267,241,NaN,241,241
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
    cols = data.columns
    temp = data[cols].values.flatten()

    s = pd.Series(temp)
    s = s.str.strip()
    s = s.values.reshape(data.shape)

    data = pd.DataFrame(s, columns=data.columns)
    data.head()

,Condition,Symptom1,Symptom2,Symptom3,Symptom4,Symptom5,Symptom6,Symptom7,Symptom8,Symptom9,...,Symptom20,Symptom21,Symptom22,Symptom23,Symptom24,Symptom25,Symptom26,Symptom27,Symptom28,Symptom26.1
0,Peripheral Nervous System Diseases,Body Weight,Drug effect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Hypertension,Body Weight,Drug effect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Toxoplasmosis, Animal",Body Weight,Drug effect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Prostatic Neoplasms,Body Weight,Drug effect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Epilepsy;Vision Disorders,Vision Disorders,Drug side effect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
data.iloc[1087272][:]

Condition        Tuberculosis
Symptom1          cover mouth
Symptom2       consult doctor
Symptom3           medication
Symptom4                 rest
Symptom5                  NaN
Symptom6                  NaN
Symptom7                  NaN
Symptom8                  NaN
Symptom9                  NaN
Symptom10                 NaN
Symptom11                 NaN
Symptom12                 NaN
Symptom13                 NaN
Symptom14                 NaN
Symptom15                 NaN
Symptom16                 NaN
Symptom17                 NaN
Symptom18                 NaN
Symptom19                 NaN
Symptom20                 NaN
Symptom21                 NaN
Symptom22                 NaN
Symptom23                 NaN
Symptom24                 NaN
Symptom25                 NaN
Symptom26                 NaN
Symptom27                 NaN
Symptom28                 NaN
Symptom26.1               NaN
Name: 1087272, dtype: object

In [34]:
lst = [data['Symptom1'].unique(), data['Symptom2'].unique(), data['Symptom3'].unique(), data['Symptom4'].unique(), data['Symptom5'].unique(), data['Symptom6'].unique(), data['Symptom7'].unique(), data['Symptom8'].unique(), data['Symptom9'].unique(), data['Symptom10'].unique(), data['Symptom11'].unique(), data['Symptom12'].unique(), data['Symptom13'].unique(), data['Symptom14'].unique(), data['Symptom15'].unique(), data['Symptom16'].unique(), data['Symptom17'].unique(), data['Symptom18'].unique(), data['Symptom19'].unique(), data['Symptom20'].unique(), data['Symptom21'].unique(), data['Symptom22'].unique(), data['Symptom23'].unique(), data['Symptom24'].unique(), data['Symptom25'].unique(), data['Symptom26'].unique(), data['Symptom27'].unique(), data['Symptom28'].unique(), data['Symptom26.1'].unique()]
oneHotEncoding = np.concatenate((lst), axis=0, out=None)
print(oneHotEncoding)
print(len(oneHotEncoding))

['Body Weight' 'Vision Disorders' 'Purpura' ... nan 'tremor'
 'symptom aggravating factors']
2155

In [40]:
myset = set(oneHotEncoding)
oneHotEncoding = list(myset)
oneHotEncoding = oneHotEncoding[0:]
#print(oneHotEncoding)

In [42]:
symptoms=pd.read_csv('datasets/ProcessedData/Symptoms.csv')
symptoms.head()

                   0
0  yellowing_of_eyes
1              spasm
2                NaN
3   Muscular Atrophy
4             Chills

In [49]:
oneHotEncoding = []
for x in range(len(symptoms)):
    oneHotEncoding.append(symptoms.iloc[x][0])
del oneHotEncoding[2]
print(len(oneHotEncoding))

809

In [50]:
from datetime import datetime

def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

In [20]:
start_time = timer(None)
x = 0
timer(start_time)

 Time taken: 0 hours 0 minutes and 0.0 seconds.

In [266]:
start_time = timer(None)

array = []
for x in range(1000):
    temp = [data.iloc[x][0]]
    for y in range(len(oneHotEncoding)):
        if oneHotEncoding[y] in set(data.iloc[x][:]):
            temp.append(1)
        else:
            temp.append(0)
    array.append(temp)
         
timer(start_time)

 Time taken: 0 hours 2 minutes and 41.38 seconds.

In [30]:
len(data['Condition'].unique())

4255

In [64]:
start_time = timer(None)
# Time taken: 1 hours 25 minutes and 34.24 seconds.
# Time taken: 1 hours 1 minutes and 18.4 seconds.

array = []
l = len(oneHotEncoding)+1
for x in range(87273):
    incre = 1000000
    temp = [0] * l
    temp[0] = data.iloc[x+incre][0]
    for y in range(len(data.iloc[x+incre][:])-1):
        if type(data.iloc[x+incre][y+1]) == type("str"):
          index = oneHotEncoding.index(data.iloc[x+incre][y+1])+1
          temp[index] = 1
    array.append(temp)
            
timer(start_time)

 Time taken: 0 hours 6 minutes and 19.39 seconds.

In [65]:
col = np.concatenate((['Condition'],oneHotEncoding), axis=0, out=None)
saveData = pd.DataFrame(array, columns=col)
saveData.to_csv('datasets/ProcessedData/oneHotEncodedSymptoms5.csv', index = False)

In [67]:
test=pd.read_csv('datasets/ProcessedData/oneHotEncodedSymptoms5.csv')
test.head()

,Condition,yellowing_of_eyes,spasm,Muscular Atrophy,Chills,homelessness,para 2,Athetosis,gag,avoid too many products,...,use ice to compress itching,get away from trigger,hypertonicity,systolic murmur,Pupil Disorders,Overweight,Stahli's line,Body Weight Changes,symptom aggravating factors,hypersomnolence
0,Paraplegia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Paraplegia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Paraplegia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Paraplegia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Paraplegia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [79]:
#print(oneHotEncoding.index("Drug side effect"))
#print(len(testing[0]))
oneHotEncoding.index('rest')

619

In [82]:
test.iloc[87272][620]

1

In [24]:
#print(array[1][530])
#import csv

print('hi')
x = [1,2,3,4]
npa = np.asarray(x, dtype=np.float32)
np.savetxt("testSave2.csv", npa, delimiter=",")

hi

In [ ]:
#'Drug effect' in set(data.iloc[0][:])

In [175]:
#set(data.iloc[0][:])

{'Body Weight', 'Drug effect', 'Peripheral Nervous System Diseases', nan, nan}

In [22]:
col = np.concatenate((['Condition'],oneHotEncoding), axis=0, out=None)
saveData = pd.DataFrame(array, columns=col)
saveData.to_csv('datasets/ProcessedData/oneHotEncodedSymptoms.csv', index = False)
test=pd.read_csv('datasets/ProcessedData/oneHotEncodedSymptoms.csv')
test.head()

MemoryError: Unable to allocate 6.55 GiB for an array with shape (809, 1087273) and data type int64

In [89]:
conditions = pd.DataFrame(data['Condition'].unique(), columns = ['Condition'])

In [92]:
conditions.to_csv('./datasets/ProcessedData/Conditions2.csv', index = False)

In [93]:
test2=pd.read_csv('./datasets/ProcessedData/Conditions2.csv')
test2.

                            Condition
0  Peripheral Nervous System Diseases
1                        Hypertension
2               Toxoplasmosis, Animal
3                 Prostatic Neoplasms
4           Epilepsy;Vision Disorders