In [1]:
#this file deletes single rows from the dataset; ie. if there is no time series; ie. if there is only 1-2 entries of that instance
#ie. time: new patient: 0, 5, 10, 15, 20, 25; new patient: 0, 1; new patient, 0, 10, 20, 30, 40, 50; take out the 0,1 guy

In [2]:
import pandas as pd
import numpy as np
import math
#import modin.pandas as pd

In [3]:
df1 = pd.read_csv(
     '../FormattedData/stage5_1d.csv'
)

In [4]:
df1

,Unnamed: 0,pt_identifier,positive_diag,negative_diag,new_date,BP1,BP2,Pulse,Temp,RR,...,Age_Number,Male,Female,Weight,Most_responsible,pre_admit,post_admit,secondary,Lactate_adjusted,WBC_adjusted
0,0,H1000412,0,1,0.0,125.0,79.0,96.0,37.4,13.0,...,81.0,0,1,NaN,0,0,0,0,0.0,0.000000
1,1,H1000412,0,1,23.0,NaN,NaN,NaN,NaN,NaN,...,81.0,0,1,NaN,0,0,0,0,0.0,0.945455
2,2,H1000412,0,1,450.0,138.0,76.0,98.0,36.8,16.0,...,81.0,0,1,NaN,0,0,0,0,0.0,0.000000
3,3,H1000412,0,1,467.0,NaN,NaN,NaN,NaN,NaN,...,81.0,0,1,NaN,0,0,0,0,0.0,1.090909
4,4,H1000412,0,1,531.0,116.0,84.0,88.0,36.9,17.0,...,81.0,0,1,NaN,0,0,0,0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312753,312753,Z991743,0,1,4209.0,153.0,64.0,58.0,36.5,16.0,...,92.0,0,1,63.0,0,0,0,0,0.0,0.000000
312754,312754,Z991743,0,1,4219.0,NaN,NaN,NaN,NaN,NaN,...,92.0,0,1,63.0,0,0,0,0,0.0,0.800000
312755,312755,Z991743,0,1,4947.0,152.0,65.0,63.0,36.6,18.0,...,92.0,0,1,63.0,0,0,0,0,0.0,0.000000
312756,312756,Z991743,0,1,5661.0,174.0,70.0,69.0,36.7,16.0,...,92.0,0,1,63.0,0,0,0,0,0.0,0.000000
312757,312757,Z992617,0,1,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,NaN,0,0,0,0,0.0,1.190909

In [5]:
del df1["Unnamed: 0"]

In [6]:
df1

,pt_identifier,positive_diag,negative_diag,new_date,BP1,BP2,Pulse,Temp,RR,O2Sat,Age_Number,Male,Female,Weight,Most_responsible,pre_admit,post_admit,secondary,Lactate_adjusted,WBC_adjusted
0,H1000412,0,1,0.0,125.0,79.0,96.0,37.4,13.0,96.0,81.0,0,1,NaN,0,0,0,0,0.0,0.000000
1,H1000412,0,1,23.0,NaN,NaN,NaN,NaN,NaN,NaN,81.0,0,1,NaN,0,0,0,0,0.0,0.945455
2,H1000412,0,1,450.0,138.0,76.0,98.0,36.8,16.0,98.0,81.0,0,1,NaN,0,0,0,0,0.0,0.000000
3,H1000412,0,1,467.0,NaN,NaN,NaN,NaN,NaN,NaN,81.0,0,1,NaN,0,0,0,0,0.0,1.090909
4,H1000412,0,1,531.0,116.0,84.0,88.0,36.9,17.0,97.0,81.0,0,1,NaN,0,0,0,0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312753,Z991743,0,1,4209.0,153.0,64.0,58.0,36.5,16.0,96.0,92.0,0,1,63.0,0,0,0,0,0.0,0.000000
312754,Z991743,0,1,4219.0,NaN,NaN,NaN,NaN,NaN,NaN,92.0,0,1,63.0,0,0,0,0,0.0,0.800000
312755,Z991743,0,1,4947.0,152.0,65.0,63.0,36.6,18.0,94.0,92.0,0,1,63.0,0,0,0,0,0.0,0.000000
312756,Z991743,0,1,5661.0,174.0,70.0,69.0,36.7,16.0,92.0,92.0,0,1,63.0,0,0,0,0,0.0,0.000000
312757,Z992617,0,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0.0,1.190909

In [7]:
rows = len(df1)
rows

312758

In [8]:
print (df1.iloc[65][3])
print (type(df1.iloc[65][3]))
#row column

45.0
<class 'numpy.float64'>

In [9]:
i=0
to_drop = []


while i<rows-2:
    value1 = df1.iloc[i][3]
    value2 = df1.iloc[i+1][3]
    value3 = df1.iloc[i+2][3]

    if value1 == 0.0 or value1 == 0:
        if value2 == 0.0 or value2 == 0:
            to_drop.append(i)

        elif value3 == 0.0 or value3 == 0:
            to_drop.append(i)
            to_drop.append(i+1)

    i+=1
    
print(len(to_drop))
print(to_drop)

3863

In [10]:
df1 = df1.drop(to_drop)
df1

,pt_identifier,positive_diag,negative_diag,new_date,BP1,BP2,Pulse,Temp,RR,O2Sat,Age_Number,Male,Female,Weight,Most_responsible,pre_admit,post_admit,secondary,Lactate_adjusted,WBC_adjusted
0,H1000412,0,1,0.0,125.0,79.0,96.0,37.4,13.0,96.0,81.0,0,1,NaN,0,0,0,0,0.0,0.000000
1,H1000412,0,1,23.0,NaN,NaN,NaN,NaN,NaN,NaN,81.0,0,1,NaN,0,0,0,0,0.0,0.945455
2,H1000412,0,1,450.0,138.0,76.0,98.0,36.8,16.0,98.0,81.0,0,1,NaN,0,0,0,0,0.0,0.000000
3,H1000412,0,1,467.0,NaN,NaN,NaN,NaN,NaN,NaN,81.0,0,1,NaN,0,0,0,0,0.0,1.090909
4,H1000412,0,1,531.0,116.0,84.0,88.0,36.9,17.0,97.0,81.0,0,1,NaN,0,0,0,0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312753,Z991743,0,1,4209.0,153.0,64.0,58.0,36.5,16.0,96.0,92.0,0,1,63.0,0,0,0,0,0.0,0.000000
312754,Z991743,0,1,4219.0,NaN,NaN,NaN,NaN,NaN,NaN,92.0,0,1,63.0,0,0,0,0,0.0,0.800000
312755,Z991743,0,1,4947.0,152.0,65.0,63.0,36.6,18.0,94.0,92.0,0,1,63.0,0,0,0,0,0.0,0.000000
312756,Z991743,0,1,5661.0,174.0,70.0,69.0,36.7,16.0,92.0,92.0,0,1,63.0,0,0,0,0,0.0,0.000000
312757,Z992617,0,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0.0,1.190909

In [11]:
df1.head(50)

,pt_identifier,positive_diag,negative_diag,new_date,BP1,BP2,Pulse,Temp,RR,O2Sat,Age_Number,Male,Female,Weight,Most_responsible,pre_admit,post_admit,secondary,Lactate_adjusted,WBC_adjusted
0,H1000412,0,1,0.0,125.0,79.0,96.0,37.4,13.0,96.0,81.0,0,1,NaN,0,0,0,0,0.000000,0.000000
1,H1000412,0,1,23.0,NaN,NaN,NaN,NaN,NaN,NaN,81.0,0,1,NaN,0,0,0,0,0.000000,0.945455
2,H1000412,0,1,450.0,138.0,76.0,98.0,36.8,16.0,98.0,81.0,0,1,NaN,0,0,0,0,0.000000,0.000000
3,H1000412,0,1,467.0,NaN,NaN,NaN,NaN,NaN,NaN,81.0,0,1,NaN,0,0,0,0,0.000000,1.090909
4,H1000412,0,1,531.0,116.0,84.0,88.0,36.9,17.0,97.0,81.0,0,1,NaN,0,0,0,0,0.000000,0.000000
5,H1000412,0,1,763.0,126.0,64.0,69.0,37.0,10.0,94.0,81.0,0,1,NaN,0,0,0,0,0.000000,0.000000
6,H1000412,0,1,929.0,NaN,NaN,NaN,NaN,NaN,NaN,81.0,0,1,NaN,0,0,0,0,0.000000,1.009091
9,H1002797,0,1,0.0,166.0,90.0,58.0,36.7,18.0,99.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
10,H1002797,0,1,166.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.554545
11,H1002797,0,1,168.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.272727,0.000000
12,H1002797,0,1,6507.0,151.0,90.0,61.0,36.0,20.0,100.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
13,H1002797,0,1,6525.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.590909
14,H1002797,0,1,6530.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.500000,0.000000
15,H1002797,0,1,6966.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.600000
16,H1002797,0,1,8663.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.936364
17,H1002797,0,1,8949.0,149.0,92.0,71.0,37.1,16.0,96.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
18,H1002797,0,1,9633.0,144.0,87.0,76.0,36.9,18.0,94.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
19,H1002797,0,1,9943.0,138.0,78.0,79.0,36.6,18.0,94.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
20,H1002797,0,1,10054.0,131.0,78.0,56.0,36.9,18.0,98.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
21,H1002797,0,1,10584.0,128.0,75.0,62.0,36.9,18.0,98.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
22,H1002797,0,1,10794.0,140.0,82.0,59.0,36.9,18.0,94.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
23,H1002797,0,1,0.0,149.0,87.0,67.0,36.7,18.0,100.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
24,H1002797,0,1,41.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.436364
25,H1002797,0,1,338.0,147.0,91.0,63.0,NaN,18.0,97.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
26,H1002797,0,1,0.0,146.0,85.0,62.0,36.5,16.0,99.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
27,H1002797,0,1,84.0,140.0,82.0,57.0,36.8,18.0,98.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
28,H1002797,0,1,90.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.600000
29,H1002797,0,1,220.0,137.0,81.0,58.0,36.8,17.0,97.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
30,H1002797,0,1,284.0,131.0,81.0,65.0,NaN,18.0,99.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
32,H1003037,0,1,0.0,102.0,53.0,108.0,36.8,22.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
33,H1003037,0,1,13.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,1.680769,0.000000
34,H1003037,0,1,13.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.000000,0.018182
35,H1003037,0,1,0.0,94.0,62.0,80.0,36.3,18.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
36,H1003037,0,1,43.0,99.0,63.0,98.0,36.9,16.0,97.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
37,H1003037,0,1,80.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.000000,0.663636
38,H1003037,0,1,0.0,105.0,47.0,106.0,36.4,17.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
39,H1003037,0,1,105.0,82.0,35.0,93.0,NaN,16.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
40,H1003037,0,1,110.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.000000,0.981818
41,H1003037,0,1,192.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.965385,0.000000
42,H1003037,0,1,198.0,105.0,50.0,69.0,NaN,18.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
43,H1003037,0,1,282.0,111.0,46.0,95.0,NaN,16.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
44,H1003037,0,1,322.0,134.0,58.0,104.0,NaN,16.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
45,H1003037,0,1,439.0,126.0,43.0,95.0,NaN,16.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
46,H1003037,0,1,532.0,118.0,51.0,80.0,36.7,18.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
47,H1003037,0,1,887.0,100.0,26.0,66.0,NaN,16.0,99.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
48,H1003037,0,1,1108.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.392308,0.000000
49,H1003037,0,1,1108.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.000000,0.600000
50,H1003037,0,1,1398.0,136.0,69.0,70.0,36.8,16.0,99.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
51,H1003037,0,1,1618.0,127.0,62.0,75.0,36.7,14.0,98.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
52,H1003037,0,1,1983.0,134.0,68.0,74.0,36.7,14.0,99.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000

In [12]:
df1 = df1.reset_index(drop=True)
df1.head(50)

,pt_identifier,positive_diag,negative_diag,new_date,BP1,BP2,Pulse,Temp,RR,O2Sat,Age_Number,Male,Female,Weight,Most_responsible,pre_admit,post_admit,secondary,Lactate_adjusted,WBC_adjusted
0,H1000412,0,1,0.0,125.0,79.0,96.0,37.4,13.0,96.0,81.0,0,1,NaN,0,0,0,0,0.000000,0.000000
1,H1000412,0,1,23.0,NaN,NaN,NaN,NaN,NaN,NaN,81.0,0,1,NaN,0,0,0,0,0.000000,0.945455
2,H1000412,0,1,450.0,138.0,76.0,98.0,36.8,16.0,98.0,81.0,0,1,NaN,0,0,0,0,0.000000,0.000000
3,H1000412,0,1,467.0,NaN,NaN,NaN,NaN,NaN,NaN,81.0,0,1,NaN,0,0,0,0,0.000000,1.090909
4,H1000412,0,1,531.0,116.0,84.0,88.0,36.9,17.0,97.0,81.0,0,1,NaN,0,0,0,0,0.000000,0.000000
5,H1000412,0,1,763.0,126.0,64.0,69.0,37.0,10.0,94.0,81.0,0,1,NaN,0,0,0,0,0.000000,0.000000
6,H1000412,0,1,929.0,NaN,NaN,NaN,NaN,NaN,NaN,81.0,0,1,NaN,0,0,0,0,0.000000,1.009091
7,H1002797,0,1,0.0,166.0,90.0,58.0,36.7,18.0,99.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
8,H1002797,0,1,166.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.554545
9,H1002797,0,1,168.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.272727,0.000000
10,H1002797,0,1,6507.0,151.0,90.0,61.0,36.0,20.0,100.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
11,H1002797,0,1,6525.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.590909
12,H1002797,0,1,6530.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.500000,0.000000
13,H1002797,0,1,6966.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.600000
14,H1002797,0,1,8663.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.936364
15,H1002797,0,1,8949.0,149.0,92.0,71.0,37.1,16.0,96.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
16,H1002797,0,1,9633.0,144.0,87.0,76.0,36.9,18.0,94.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
17,H1002797,0,1,9943.0,138.0,78.0,79.0,36.6,18.0,94.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
18,H1002797,0,1,10054.0,131.0,78.0,56.0,36.9,18.0,98.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
19,H1002797,0,1,10584.0,128.0,75.0,62.0,36.9,18.0,98.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
20,H1002797,0,1,10794.0,140.0,82.0,59.0,36.9,18.0,94.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
21,H1002797,0,1,0.0,149.0,87.0,67.0,36.7,18.0,100.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
22,H1002797,0,1,41.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.436364
23,H1002797,0,1,338.0,147.0,91.0,63.0,NaN,18.0,97.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
24,H1002797,0,1,0.0,146.0,85.0,62.0,36.5,16.0,99.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
25,H1002797,0,1,84.0,140.0,82.0,57.0,36.8,18.0,98.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
26,H1002797,0,1,90.0,NaN,NaN,NaN,NaN,NaN,NaN,66.0,0,1,NaN,0,0,0,0,0.000000,0.600000
27,H1002797,0,1,220.0,137.0,81.0,58.0,36.8,17.0,97.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
28,H1002797,0,1,284.0,131.0,81.0,65.0,NaN,18.0,99.0,66.0,0,1,NaN,0,0,0,0,0.000000,0.000000
29,H1003037,0,1,0.0,102.0,53.0,108.0,36.8,22.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
30,H1003037,0,1,13.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,1.680769,0.000000
31,H1003037,0,1,13.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.000000,0.018182
32,H1003037,0,1,0.0,94.0,62.0,80.0,36.3,18.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
33,H1003037,0,1,43.0,99.0,63.0,98.0,36.9,16.0,97.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
34,H1003037,0,1,80.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.000000,0.663636
35,H1003037,0,1,0.0,105.0,47.0,106.0,36.4,17.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
36,H1003037,0,1,105.0,82.0,35.0,93.0,NaN,16.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
37,H1003037,0,1,110.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.000000,0.981818
38,H1003037,0,1,192.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.965385,0.000000
39,H1003037,0,1,198.0,105.0,50.0,69.0,NaN,18.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
40,H1003037,0,1,282.0,111.0,46.0,95.0,NaN,16.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
41,H1003037,0,1,322.0,134.0,58.0,104.0,NaN,16.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
42,H1003037,0,1,439.0,126.0,43.0,95.0,NaN,16.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
43,H1003037,0,1,532.0,118.0,51.0,80.0,36.7,18.0,100.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
44,H1003037,0,1,887.0,100.0,26.0,66.0,NaN,16.0,99.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
45,H1003037,0,1,1108.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.392308,0.000000
46,H1003037,0,1,1108.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,1,0,88.0,0,0,0,0,0.000000,0.600000
47,H1003037,0,1,1398.0,136.0,69.0,70.0,36.8,16.0,99.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
48,H1003037,0,1,1618.0,127.0,62.0,75.0,36.7,14.0,98.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000
49,H1003037,0,1,1983.0,134.0,68.0,74.0,36.7,14.0,99.0,65.0,1,0,88.0,0,0,0,0,0.000000,0.000000

In [ ]:
df1.to_csv('stage5_1e.csv')